os:
  - osx
  - linux
language: node_js
node_js:
  - "9"
install:
  - npm install
env:
  - GAUGE_TELEMETRY_ENABLED=false GAUGE_PREFIX=/tmp
script:
  - npm test
  - cd ..
  - git clone --depth=1 https://github.com/getgauge/gauge-tests
  - cd gauge-tests
  - curl -sSfL https://raw.githubusercontent.com/getgauge/infrastructure/master/nightly_scripts/install_latest_gauge_nightly.sh | bash
  - export PATH=/tmp/bin:$PATH
  - gauge -v
  - cd $TRAVIS_BUILD_DIR
  - npm run installPlugin
  - cd ..
  - cd gauge-tests
  - echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> ~/.gauge/config/gauge.properties
  - gauge install
  - gauge -v
  - TAGS="js" ./starttests.sh js
